version: "3.5"

services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - fluentd
    restart: always
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.access
    networks:
      - logging
