version: "3.5"
services:
  web:
    image: httpd
    container_name: httpd
    depends_on:
      - fluentd
    ports:
      - "8080:80"
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    networks:
      - logging
